apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-shop
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '5000'
        prometheus.io/path: '/metrics'
      labels:
        app: fake-shop
    spec:
      initContainers:
        - name: check-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w30 postgres 5432; do echo "Waiting for Postgres"; sleep 5; done; echo "Postgres is up"']
      containers:
      - name: fake-shop
        image: rafallltm/fake-shop:v1
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: fake-shop-db-secrets
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fake-shop-db-secrets
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: fake-shop-db-secrets
              key: POSTGRES_DB
        - name: FLASK_APP
          value: index.py
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
            
---

apiVersion: v1
kind: Service
metadata:
  name: fake-shop
spec:
  selector:
    app: fake-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer