name: CI-CD

on:
  push:
    branches:
      - rtm
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Fazer checkout do c贸digo
      - name: Checkout do c贸digo
        uses: actions/checkout@v4

      # Fazer login no Docker Hub
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Construir e enviar a imagem Docker
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            rafallltm/fake-shop:latest
            rafallltm/fake-shop:v${{ github.run_number }}
            
  cd:
    runs-on: ubuntu-latest
    needs: ci
    permissions:
      id-token: write
      contents: read
      actions: read

    steps:
      # Fazer checkout do c贸digo
      - name: Checkout do codigo
        run: echo "Fazendo checkout do c贸digo..."
      
      # Autenticar na AWS
      - name: Autenticar na AWS
        run: echo "Autenticando na AWS com chave de acesso e chave secreta..."
      
      # Atualizar kubeconfig
      - name: Configurar kubectl
        run: echo "Atualizando kubeconfig com o nome k8s-aws..."
      
      # Deploy no Kubernetes  
      - name: Deploy to Kubernetes
        run: echo "Fazendo deploy no Kubernetes..."